
DELETE http://localhost:3003/api/blogs/65ef1edb16d8bd867773127a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlZXBlZSIsImlkIjoiNjVlZjEwOGQ4Y2MxNDY3NTYwMzUwMjNmIiwiaWF0IjoxNzEwMTY5ODc0fQ.dLL8BfON9J2u1mQWZN7BZfu44mJVTNfaLyp81IsFm7E