services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

  app:
    image: bloglist-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    container_name: bloglist-frontend-dev
    depends_on:
      - server

  server:
    image: bloglist-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    container_name: bloglist-backend-dev
    env_file:
      - ./backend/.env

  debug-helper:
    image: busybox
